name: Dependency Submission

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dependency submission (Python)
        uses: advanced-security/component-detection-dependency-submission-action@v0.0.2
        continue-on-error: true
